### PR TITLE
Blog post to launch EOY giving campaign.

### PR DESCRIPTION
**Pull request by OscarSiba**
@kariljordan @elletjies Please review, and when done, tag Maneesha and Rob for one of them to merge. Please do not merge it yourself. 

---

### CODE REVIEW

**Comment by elletjies** [comment]
@OscarSiba the blog post is good to go - do we have any photos or something else we can share? Also, the [deploy preview ](https://deploy-preview-311--carp-new-website.netlify.app/)link does not work.

**Review by elletjies — APPROVED** [review]

**Comment by OscarSiba** [comment]
@maneesha This is good to merge. @kariljordan had already given her review prior to me creating a PR.

**Comment by OscarSiba** [comment]
> @OscarSiba the blog post is good to go - do we have any photos or something else we can share? Also, the [deploy preview ](https://deploy-preview-311--carp-new-website.netlify.app/)link does not work.

We will not be including any photos in this blog, thanks @elletjies. There is a graphic that will accompany the social media announcement though.

**Comment by maneesha** [comment]
I have reviewed this blog post and made the following changes:

* use relative links within carpentries.org
* use the donation site variable
* formatted buttons for donation link
* move the file to the month 12 folder from the month 11 folder

@elletjies You can't see the preview because the publication date is in the future.

**Review by maneesha — APPROVED** [review]
See my previous comment for changes I made.  I will merge this shortly.

**Pull request merged**
